#!/bin/bash

# Usage:
#     ./checker <url> [<delay (in seconds, default: 60)>] [<action to be done at url when change is detected (default: chromium)>]
#
#     Press CTRL+C to exit infinite loop.
#
# Author: quetzelcoatlus (https://github.com/quetzelcoatlus), AD 2018

trap 'echo " Okay, I will stop. Bye :)"; exit 2' INT

if [ -z $1 ]
then
	echo "Usage: ./checker <url> [<delay (in seconds, default: 60)>] [<action to be done at url when change is detected (default: chromium)>]"
	exit 1
fi

declare -r url=${1}
declare -r delay=${2:-60}
declare -r action=${3:-chromium}

prev=`curl -s -H 'Cache-Control: no-cache' "${url}" | md5sum | awk '{printf $1}'`

while true
do
	hash=`curl -s -H 'Cache-Control: no-cache' "${url}" | md5sum | awk '{printf $1}'`
	if [ "${prev}" != "${hash}" ]
	then
		eval ${action} ${url}
		exit 0
	fi
	prev=${hash}
	sleep ${delay}
done
